# Generated by Django 5.1.6 on 2025-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_blog_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='media/projects/gallery_images/'),
        ),
    ]
