# Generated by Django 5.1.6 on 2025-06-20 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_comment_options_rename_message_comment_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-featured', '-end_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.AddField(
            model_name='project',
            name='challenges_and_solutions',
            field=models.TextField(blank=True, help_text='Describe challenges encountered and their solutions.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description',
            field=models.TextField(blank=True, help_text='Detailed description for the project modal.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(blank=True, help_text='List key features, one per line or use Markdown.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Short description for project card and overview.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image for project card/thumbnail.', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional, smaller thumbnail image.', null=True, upload_to='projects/thumbnails/'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which images appear in the gallery.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('project', 'order')},
            },
        ),
    ]
