# Generated by Django 5.1.6 on 2025-06-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_blog_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
