# Generated by Django 5.1.6 on 2025-06-24 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_blog_likes_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-date_given', 'name'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Only approved testimonials will be visible on the site'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Optional: Image of the person giving the testimonial', null=True, upload_to='testimonials/avatars/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, help_text='Company the person works for', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='date_given',
            field=models.DateField(auto_now_add=True, default='2025-06-24', help_text='Date the testimonial was added'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='featured',
            field=models.BooleanField(default=False, help_text='Check to display this testimonial on the homepage'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(help_text='Name of the person giving the testimonial', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5, help_text='Rating out of 5 stars (1 being lowest, 5 highest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, help_text='Role or title of the person (e.g., CEO, Marketing Manager)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_text',
            field=models.TextField(help_text='The actual testimonial content'),
        ),
    ]
